server:
  port: 8082
eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9099/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurants
    username: root
    password: 1007321243
  application:
    name: RESTAURANT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

